### ISSUE TITLE
Returns nullptr when parsing "0."

### ISSUE THREAD

**Issue by zhihaoy** [lemire/fast_double_parser#40]
Microsoft Windows [Version 10.0.19042.610]
Microsoft Visual Studio Community 2019
Version 16.7.7

**Comment by lemire** [comment]
We follow RFC 7159. Please see https://tools.ietf.org/html/rfc7159
 

>  A fraction part is a decimal point followed by one or more digits.


The string "0." is an invalid number string as per RFC 7159. Thus it should be rejected.

**Comment by lemire** [comment]
It works as expected. I will add further clarification to the README.

**Comment by lemire** [comment]
You may want to consider https://github.com/lemire/fast_float if you are not interested in RC 7159.

**Comment by wojdyr** [comment]
Are there any variants (perhaps integrated with other software) that would parse the same strings as `strtod`,
but without specifying the end pointer?
I've been considering wrapping from_chars, but
* `from_chars(s, s+strlen(s), ...)` may be slow,
* `from_chars(s, s+100, ...)` would (I suppose) cause UB.

**Comment by lemire** [comment]
@wojdyr 

> from_chars(s, s+strlen(s), ...) may be slow,

Parsing a float takes hundreds of instructions, how many instructions do you expect `strlen(s)` to be?

**Comment by wojdyr** [comment]
Checking it, I get 20-40 instructions for my use cases, so it's not slow.
I had in the back of my head [this story][1] about GTA Online being slow because of strlen, but they had really long strings.

Interestingly, when I tried this minimal program:

```cpp
#include <cstring>
#include <cstdio>
#include "fast_float/fast_float.h"

int main(int, char** argv) {
    const char* s = argv[1];
    double x;
    //auto answer = fast_float::from_chars(s, s + 3, x);
    auto answer = fast_float::from_chars(s, s + std::strlen(s), x);
    if (answer.ec == std::errc()) {
        std::printf("OK: %g\n", x);
    } else {
        std::printf("BAD\n");
    }
    return 0;
}
```

replacing `s + 3` with `s + std::strlen(s)` adds almost 1000 instructions. But I guess something else got optimized with `s + 3`.
I tested it with:

    $ g++-10 -O3 -Wall -W a.cpp -I../include
    $ valgrind --tool=cachegrind ./a.out "3.1"

and took `I   refs` as the instruction count.

Anyway, I'll go with strlen.

Is the only difference in the accepted strings between strtod and from_chars that the former accepts preceding `+` and white space?

[1]: https://nee.lv/2021/02/28/How-I-cut-GTA-Online-loading-times-by-70/

**Comment by lemire** [comment]
If you are concerned with performance and you are using C++, I recommend adopting `std::string_view` or the equivalent. It is much, much nicer than a C string and it can deliver performance that `std::string` just can't give you.
